stages:
  - test
  - build
  - publish

image: parity/rust:gitlab-ci

variables:
  RUST_BACKTRACE: "1"
  CI_SERVER_NAME: "GitLab CI"
  LIBSSL: "libssl1.0.0 (>=1.0.0)"
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"

cache:
  key: "$CI_JOB_NAME"
  paths:
    - target/
    - cargo/

.releaseable_branches: # list of git refs for building GitLab artifacts (think "pre-release binaries")
  only: &releaseable_branches
    - master
    - stable
    - beta
    - tags

.publishable_branches: # list of git refs for publishing builds to the "production" locations
  only: &publishable_branches
    - schedules # Our nightly builds from schedule, on `master`
    - "v*" # Our version tags

.collect_artifacts: &collect_artifacts
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: on_success
    expire_in: 1 mos
    paths:
    - artifacts/


#### stage: test

test:rust:stable: &test
  stage: test
  script:
    - scripts/gitlab/test.sh stable
  tags:
    - rust-stable

.optional_test: &optional_test
  <<: *test
  allow_failure: true
  only:
    - triggers
    - master

test:rust:beta:
  <<: *optional_test
  script:
    - scripts/gitlab/test.sh beta

test:rust:nightly:
  <<: *optional_test
  script:
    - scripts/gitlab/test.sh nightly

#test:rustfmt:
#  <<: *optional_test
#  script:
#    - scripts/gitlab/rustfmt.sh

#test:clippy:
#  <<: *optional_test
#  script:
#    - scripts/gitlab/clippy.sh

test:coverage:
  stage: test
  only:
    - master
  script:
    - scripts/gitlab/coverage.sh
  tags:
    - kcov
  allow_failure: true

#### stage: build

linux:ubuntu:x86_64:
  stage: build
  only: *releaseable_branches
  script:
    - rustup default stable
    # ARGUMENTS: 1. BUILD_PLATFORM (target for binaries) 2. PLATFORM (target for cargo) 3. ARC (architecture) 4. & 5. CC & CXX flags 6. binary identifier
    - scripts/gitlab/build.sh x86_64-unknown-linux-gnu x86_64-unknown-linux-gnu amd64 gcc g++ ubuntu
  tags:
    - rust-stable
  <<: *collect_artifacts

linux:debian:x86_64:
  stage: build
  only: *releaseable_branches
  image: parity/rust-debian:gitlab-ci
  variables:
    LIBSSL: "libssl1.1 (>=1.1.0)"
  script:
    - scripts/gitlab/build.sh x86_64-unknown-debian-gnu x86_64-unknown-linux-gnu amd64 gcc g++ debian
  tags:
    - rust-debian
  <<: *collect_artifacts

linux:centos:x86_64:
  stage: build
  only: *releaseable_branches
  image: parity/rust-centos:gitlab-ci
  script:
    - scripts/gitlab/build.sh x86_64-unknown-centos-gnu x86_64-unknown-linux-gnu x86_64 gcc g++ centos
  tags:
    - rust-centos
  <<: *collect_artifacts

linux:ubuntu:i686:
  stage: build
  only: *releaseable_branches
  image: parity/rust-i686:gitlab-ci
  script:
    - scripts/gitlab/build.sh i686-unknown-linux-gnu i686-unknown-linux-gnu i386 gcc g++ ubuntu
  tags:
    - rust-i686
  <<: *collect_artifacts

linux:ubuntu:armv7:
  stage: build
  only: *releaseable_branches
  image: parity/rust-armv7:gitlab-ci
  script:
    - scripts/gitlab/build.sh armv7-unknown-linux-gnueabihf armv7-unknown-linux-gnueabihf armhf arm-linux-gnueabihf-gcc arm-linux-gnueabihf-g++ ubuntu
  tags:
    - rust-arm
  <<: *collect_artifacts

linux:ubuntu:arm:
  stage: build
  only: *releaseable_branches
  image: parity/rust-arm:gitlab-ci
  script:
    - scripts/gitlab/build.sh arm-unknown-linux-gnueabihf arm-unknown-linux-gnueabihf armhf arm-linux-gnueabihf-gcc arm-linux-gnueabihf-g++ ubuntu
  tags:
    - rust-arm
  <<: *collect_artifacts

linux:ubuntu:aarch64:
  stage: build
  only: *releaseable_branches
  image: parity/rust-arm64:gitlab-ci
  script:
    - scripts/gitlab/build.sh aarch64-unknown-linux-gnu aarch64-unknown-linux-gnu arm64 aarch64-linux-gnu-gcc aarch64-linux-gnu-g++ ubuntu
  tags:
    - rust-arm
  <<: *collect_artifacts

linux:snap:x86_64:
  stage: build
  only: *releaseable_branches
  image: parity/rust:gitlab-ci
  script:
    - scripts/gitlab/build.sh x86_64-unknown-snap-gnu x86_64-unknown-linux-gnu amd64 gcc g++ snap
  tags:
    - rust-stable
  <<: *collect_artifacts

linux:snap:i386:
  stage: build
  only: *releaseable_branches
  image: parity/rust-i686:gitlab-ci
  script:
    - scripts/gitlab/build.sh i686-unknown-snap-gnu i686-unknown-linux-gnu i386 gcc g++ snap
  tags:
    - rust-stable
  <<: *collect_artifacts

linux:snap:arm64:
  stage: build
  only: *releaseable_branches
  image: parity/rust-arm64:gitlab-ci
  script:
    - scripts/gitlab/build.sh arm64-unknown-snap-gnu aarch64-unknown-linux-gnu arm64 aarch64-linux-gnu-gcc aarch64-linux-gnu-g++ snap
  tags:
    - rust-stable
  <<: *collect_artifacts

linux:snap:armhf:
  stage: build
  only: *releaseable_branches
  image: parity/rust-armv7:gitlab-ci
  script:
    - scripts/gitlab/build.sh armhf-unknown-snap-gnu armv7-unknown-linux-gnueabihf armhf arm-linux-gnueabihf-gcc arm-linux-gnueabihf-g++ snap
  tags:
    - rust-stable
  <<: *collect_artifacts

macos:x86_64:
  stage: build
  only: *releaseable_branches
  script:
    - scripts/gitlab/build.sh x86_64-apple-darwin x86_64-apple-darwin macos gcc g++ macos
  tags:
    - osx
  <<: *collect_artifacts

windows:x86_64:
  stage: build
  only: *releaseable_branches
  cache:
    key: "%CI_JOB_NAME%"
    paths:
      - target/
      # No cargo caching, since fetch-locking on Windows gets stuck
  script:
    - sh scripts/gitlab/build.sh x86_64-pc-windows-msvc x86_64-pc-windows-msvc installer "" "" windows
  tags:
   - rust-windows
  <<: *collect_artifacts

#### stage: publish

docker:
  stage: publish
  only: *publishable_branches
  dependencies:
    - linux:ubuntu:x86_64
  script:
    - scripts/gitlab/docker-build.sh
  tags:
    - docker